.PHONY: clean All

All:
	@echo "----------Building project:[ WorkingWithCPPStrings - Debug ]----------"
	@cd "WorkingWithCPPStrings" && "$(MAKE)" -f  "WorkingWithCPPStrings.mk"
clean:
	@echo "----------Cleaning project:[ WorkingWithCPPStrings - Debug ]----------"
	@cd "WorkingWithCPPStrings" && "$(MAKE)" -f  "WorkingWithCPPStrings.mk" clean
