.PHONY: clean All

All:
	@echo "----------Building project:[ WorkingWithCStyleStrings - Debug ]----------"
	@cd "WorkingWithCStyleStrings" && "$(MAKE)" -f  "WorkingWithCStyleStrings.mk"
clean:
	@echo "----------Cleaning project:[ WorkingWithCStyleStrings - Debug ]----------"
	@cd "WorkingWithCStyleStrings" && "$(MAKE)" -f  "WorkingWithCStyleStrings.mk" clean
